Veins: veins::ASLAppRSU Class Reference
veins::ASLAppRSU Class Reference
This is a stub for a typical Veins application layer.
#include <ASLAppRSU.h>
Public Member Functions
void initialize (int stage) override
void initialize (int stage, int deviceType)
void finish () override
Public Member Functions inherited from veins::DemoBaseApplLayer
~DemoBaseApplLayer () override
void initialize (int stage) override
void finish () override
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Public Member Functions inherited from veins::BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void onBSM (DemoSafetyMessage *bsm) override
this function is called upon receiving a DemoSafetyMessage, also referred to as a beacon
void onWSM (BaseFrame1609_4 *wsm) override
this function is called upon receiving a BaseFrame1609_4
void onWSA (DemoServiceAdvertisment *wsa) override
this function is called upon receiving a DemoServiceAdvertisement
void onASL (ASLMessage *asl)
void onASLBSM (ASLBSM *aslBsm)
void populateASL (ASLMessage *asl, LAddress::L2Type senderId, LAddress::L2Type rcvId)
void populateWSM (BaseFrame1609_4 *wsm, LAddress::L2Type senderId, LAddress::L2Type rcvId)
void checkAndTrackPacket (cMessage *msg) override
helper function for error handling and stats recording purposes
void handleLowerMsg (cMessage *msg) override
handle messages from below and calls the onWSM, onBSM, and onWSA functions accordingly
void handleSelfMsg (cMessage *msg) override
handle self messages
void handlePositionUpdate (cObject *obj) override
this function is called every time the vehicle receives a position update signal
Protected Member Functions inherited from veins::DemoBaseApplLayer
virtual void populateWSM (BaseFrame1609_4 *wsm, LAddress::L2Type rcvId=LAddress::L2BROADCAST(), int serial=0)
sets all the necessary fields in the WSM, BSM, or WSA.
virtual void handleParkingUpdate (cObject *obj)
this function is called every time the vehicle parks or starts moving again
virtual void startService (Channel channel, int serviceId, std::string serviceDescription)
This will start the periodic advertising of the new service on the CCH.
virtual void stopService ()
stopping the service and advertising for it
virtual simtime_t computeAsynchronousSendingTime (simtime_t interval, ChannelType chantype)
compute a point in time that is guaranteed to be in the correct channel interval plus a random offset
virtual void sendDown (cMessage *msg)
overloaded for error handling and stats recording purposes
virtual void sendDelayedDown (cMessage *msg, simtime_t delay)
overloaded for error handling and stats recording purposes
Protected Member Functions inherited from veins::BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperMsg (cMessage *msg) override
Handle messages from upper layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
double speedLimit = 15
double L = 900
double L_int = 10
double serviceRate = 1800/3600
int deviceType
int receivedASL =0
int receivedASLBSM =0
int generatedASLs =0
int vehiclesInFront = 0
TraCITrafficLightInterface * tlsInterface
TraCICommandInterface * traci
TraCICommandInterface::Trafficlight * tlsTraci
Protected Attributes inherited from veins::DemoBaseApplLayer
TraCIMobility * mobility
TraCICommandInterface * traci
TraCICommandInterface::Vehicle * traciVehicle
AnnotationManager * annotations
DemoBaseApplLayerToMac1609_4Interface * mac
bool isParked
uint32_t beaconLengthBits
uint32_t beaconUserPriority
simtime_t beaconInterval
bool sendBeacons
uint32_t dataLengthBits
uint32_t dataUserPriority
bool dataOnSch
int currentOfferedServiceId
std::string currentServiceDescription
Channel currentServiceChannel
simtime_t wsaInterval
Coord curPosition
Coord curSpeed
LAddress::L2Type myId = 0
int mySCH
uint32_t generatedWSMs
uint32_t generatedWSAs
uint32_t generatedBSMs
uint32_t receivedWSMs
uint32_t receivedWSAs
uint32_t receivedBSMs
cMessage * sendBeaconEvt
cMessage * sendWSAEvt
Protected Attributes inherited from veins::BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from veins::BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from veins::DemoBaseApplLayer
enum DemoApplMessageKinds { SEND_BEACON_EVT, SEND_WSA_EVT }
Public Types inherited from veins::BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
This is a stub for a typical Veins application layer.
Most common functions are overloaded. See ASLApp.cc for hints
Author
David Eckhoff
Member Function Documentation
checkAndTrackPacket()
void ASLAppRSU::checkAndTrackPacket (cMessage * msg) override protected virtual
helper function for error handling and stats recording purposes
Parameters
msg the message to be checked and tracked
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayer::checkAndTrackPacket(), and generatedASLs.
 {
     if(dynamic_cast<ASLMessage*>(msg)){
         EV_TRACE << "sending down an ASL" << std::endl;
         generatedASLs++;
     }else {
         DemoBaseApplLayer::checkAndTrackPacket(msg);
     }
 }
finish()
void ASLAppRSU::finish () override
References veins::DemoBaseApplLayer::finish().
 {
     DemoBaseApplLayer::finish();
     // statistics recording goes here
 }
handleLowerMsg()
void ASLAppRSU::handleLowerMsg (cMessage * msg) override protected virtual
handle messages from below and calls the onWSM, onBSM, and onWSA functions accordingly
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayer::handleLowerMsg(), onASLBSM(), receivedASL, and receivedASLBSM.
{
     BaseFrame1609_4* wsm = dynamic_cast<BaseFrame1609_4*>(msg);
     ASSERT(wsm);
     // asl message is a unique message for this application so we do not include it in the base demo app layer
     if (ASLMessage* asl = dynamic_cast<ASLMessage*>(wsm)) {
         receivedASL++;
         //onASL(asl);
             // ignore asl messages if RSU
     }else if(ASLBSM* aslBsm = dynamic_cast<ASLBSM*>(wsm)){
         receivedASLBSM++;
         onASLBSM(aslBsm);
     }else{
         DemoBaseApplLayer::handleLowerMsg(msg);
     }
 }
handlePositionUpdate()
void ASLAppRSU::handlePositionUpdate (cObject * obj) override protected virtual
this function is called every time the vehicle receives a position update signal
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayer::handlePositionUpdate().
 {
     DemoBaseApplLayer::handlePositionUpdate(obj);
     // the vehicle has moved. Code that reacts to new positions goes here.
     // member variables such as currentPosition and currentSpeed are updated in the parent class
 }
handleSelfMsg()
void ASLAppRSU::handleSelfMsg (cMessage * msg) override protected virtual
handle self messages
Reimplemented from veins::DemoBaseApplLayer.
 {
     //DemoBaseApplLayer::handleSelfMsg(msg);
     // this method is for self messages (mostly timers)
     // it is important to call the DemoBaseApplLayer function for BSM and WSM transmission
 }
initialize() [1/2]
void ASLAppRSU::initialize (int stage) override
References veins::TraCITrafficLightInterfaceAccess::get(), veins::TraCITrafficLightInterface::getCommandInterface(), veins::TraCITrafficLightInterface::getTlCommandInterface(), veins::DemoBaseApplLayer::initialize(), veins::TraCITrafficLightInterface::setExternalId(), tlsInterface, tlsTraci, and traci.
Referenced by initialize().
 {
     DemoBaseApplLayer::initialize(stage);
     if (stage == 0) {
         // Initializing members and pointers of your application goes here
         EV << "Initializing " << par("appName").stringValue() << std::endl;
         // initialize pointers to other modules
         if (FindModule<TraCITrafficLightInterfaceAccess*>::findSubModule(getParentModule())) {
             tlsInterface = TraCITrafficLightInterfaceAccess().get(getParentModule());
             tlsInterface->setExternalId("gneJ0");
             traci = tlsInterface->getCommandInterface();
             tlsTraci = tlsInterface->getTlCommandInterface();
         }
         else {
             traci = nullptr;
         }
     }
     else if (stage == 1) {
         // Initializing members that require initialized other modules goes here
     }
     //tlsInterface = new TraCITrafficLightInterface();
     //tlsInterface->preInitialize();
 }
initialize() [2/2]
void ASLAppRSU::initialize (int stage, int deviceType)
References deviceType, and initialize().
{
     // deviceType = 0 -> vehicle
     // deviceType = 1 -> RSU
     initialize(stage);
     this->deviceType = deviceType;
 }
onASL()
void ASLAppRSU::onASL (ASLMessage * asl) protected
 {
     // Your application has received an ASL packet from an RSU
     // code for handling the message goes here, see TraciDemo11p.cc for examples
 }
onASLBSM()
void ASLAppRSU::onASLBSM (ASLBSM * aslBsm) protected
References veins::TraCITrafficLightInterface::getCurrentPhase(), veins::DemoBaseApplLayerToMac1609_4Interface::getMACAddress(), veins::TraCITrafficLightInterface::getRemainingDuration(), L, L_int, veins::Coord::length(), veins::DemoBaseApplLayer::mac, veins::DemoBaseApplLayer::myId, populateASL(), veins::DemoBaseApplLayer::sendBeaconEvt, veins::DemoBaseApplLayer::sendDown(), serviceRate, speedLimit, veins::TraCITrafficLightProgram::Phase::state, tlsInterface, vehiclesInFront, and veins::Coord::x.
Referenced by handleLowerMsg().
 {
     // Your application has received an ASL packet from an RSU
     // code for handling the message goes here, see TraciDemo11p.cc for examples
     // Your application has received a beacon message from another car or RSU
     // code for handling the message goes here
     // if this car is an RSU and it receives a BSM packet, then it will determine if it should send an ASL packet to the vehicle
     // it will check if that vehicle is past the loop detector?
    /* if(this->deviceType != 1)
         return; */
     // here the RSU will get the BSM and compute the appropriate ASL velocity if the vehicle is within the communication range
     // with heading toward the current intersection ****
     // need to access the traffic light parameters here as well
     // the name of the traffic light signal/junction will be different in each network xml. so need to be careful about that.
     simtime_t timeLeft = tlsInterface->getRemainingDuration(); // TRAFFIC LIGHT CONTROL ATTACK HERE
    /* TraCITrafficLightProgram tlProgram = tlsTraci->getProgramDefinition();
 */
     // get state and phase and check how much time until the next phase/cycle
   /*  TraCITrafficLightProgram::Phase phase = tlProgram.Phase; */
     TraCITrafficLightProgram::Phase phase = tlsInterface->getCurrentPhase(); // TRAFFIC LIGHT CONTROL ATTACK HERE
     std::cout << "The current phase state is: " << phase.state << std::endl;
     std::cout << "The remaining time is : " << timeLeft.str() << std::endl;
     // check if the heading is correct / or just check that the position is within the expected range
     // since coordinates are being used, we may need to have a coordinate range that satisfies this range
     // get their speed and calculate their arrival time
     // need to get the estimated number of vehicles in front
     // using data from the induction loop
     // makeTraCICommand()
     // arrival time = min(t + (L - L_int - position(t))/vf, tcurr + 3600* vehicles_in_front / service rate)
     // service rate = 1800/3600 vehicles per second
     // get the address of the vehicle so that we can send ASL message to it
     LAddress::L2Type senderId = aslBsm->getSenderAddress();
     Coord position = aslBsm->getSenderPos();
     Coord speed = aslBsm->getSenderSpeed();
     //double XYZPosition = convertLonLat2XY(position);
     double currPositionX = position.x; // POSITION ATTACK HERE E.G. GPS OR FAKE MSG
     double currSpeed = speed.length();
     double aslSpeed = currSpeed;
     // get speed in the X direction?
     // time at which the packet arrives to RSU is different than when vehicle sent the packet
     // so need to adjust accordingly to possible delay
     simtime_t currTime = simTime();
     simtime_t arrivalTime = currTime; // need to compute this based on current vehicle's speed and position and current traffic control phase
     // if the  car is not able to make the current red light then it needs to be put into the next green cycle
     // if the car is within the current green cycle, then it will be given a max asl speed based on the current green cycle and its current speed + current time
     // need to adapt this for 2d roads; not so straightforward
     // even more difficult with curved roads
     // VEHICLESINFRONT - INDUCTION LOOP ATTACK HERE
     arrivalTime = std::min(currTime + (L - L_int - currPositionX)/speedLimit, currTime + 3600 * vehiclesInFront / serviceRate);
     //aslSpeed = std::min(speedLimit, )
     // here we will construct an ASL message to send to the vehicle
     ASLMessage* asl = new ASLMessage();
     LAddress::L2Type myId = mac->getMACAddress();
     //ASLAppRSU::populateWSM(asl, myId, senderId);
     asl->setAslSpeed(aslSpeed); // get the average speed (sqrt (x^2 + y^2 + z^2)) // SPEED ATTACK HERE
     asl->setArrivalTime(currTime + speed.length()); // ARRIVAL TIME ATTACK HERE
     ASLAppRSU::populateASL(asl, myId, senderId);
     sendDown(asl); // send the packet
     scheduleAt(simTime(), sendBeaconEvt); // send the packet ///// COMM_DELAY ATTACK HERE
     // simTime() + beaconInterval
     //populateASL(asl);
     // DONE
 }
onBSM()
void ASLAppRSU::onBSM (DemoSafetyMessage * bsm) override protected virtual
this function is called upon receiving a DemoSafetyMessage, also referred to as a beacon
Reimplemented from veins::DemoBaseApplLayer.
 {
 }
onWSA()
void ASLAppRSU::onWSA (DemoServiceAdvertisment * wsa) override protected virtual
this function is called upon receiving a DemoServiceAdvertisement
Reimplemented from veins::DemoBaseApplLayer.
 {
     // Your application has received a service advertisement from another car or RSU
     // code for handling the message goes here, see TraciDemo11p.cc for examples
 }
onWSM()
void ASLAppRSU::onWSM (BaseFrame1609_4 * wsm) override protected virtual
this function is called upon receiving a BaseFrame1609_4
Reimplemented from veins::DemoBaseApplLayer.
 {
     // Your application has received a data message from another car or RSU
     // code for handling the message goes here, see TraciDemo11p.cc for examples
 }
populateASL()
void ASLAppRSU::populateASL (ASLMessage * asl, LAddress::L2Type senderId, LAddress::L2Type rcvId) protected
References veins::DemoBaseApplLayer::beaconLengthBits, veins::DemoBaseApplLayer::beaconUserPriority, veins::cch, and veins::BaseApplLayer::headerLength.
Referenced by onASLBSM().
{
     asl->setRecipientAddress(rcvId);
     asl->setBitLength(headerLength);
     asl->setPsid(-1);
     asl->setChannelNumber(static_cast<int>(Channel::cch));
     asl->addBitLength(beaconLengthBits);
     asl->setUserPriority(beaconUserPriority);
 }
populateWSM()
void ASLAppRSU::populateWSM (BaseFrame1609_4 * wsm, LAddress::L2Type senderId, LAddress::L2Type rcvId) protected
References veins::DemoBaseApplLayer::beaconLengthBits, veins::DemoBaseApplLayer::beaconUserPriority, veins::cch, veins::BaseApplLayer::headerLength, and veins::DemoBaseApplLayer::populateWSM().
{
     wsm->setRecipientAddress(rcvId);
     wsm->setBitLength(headerLength);
     if (ASLMessage* asl = dynamic_cast<ASLMessage*>(wsm)) {
         //aslBsm->setSenderAddress(senderId);
         //aslBsm->setSenderPos(curPosition);
         //aslBsm->setSenderSpeed(curSpeed);
         asl->setPsid(-1);
         asl->setChannelNumber(static_cast<int>(Channel::cch));
         asl->addBitLength(beaconLengthBits);
         asl->setUserPriority(beaconUserPriority);
     }else {
         DemoBaseApplLayer::populateWSM(wsm);
     }
 }
Member Data Documentation
deviceType
int veins::ASLAppRSU::deviceType protected
Referenced by initialize().
generatedASLs
int veins::ASLAppRSU::generatedASLs =0 protected
Referenced by checkAndTrackPacket().
L
double veins::ASLAppRSU::L = 900 protected
Referenced by onASLBSM().
L_int
double veins::ASLAppRSU::L_int = 10 protected
Referenced by onASLBSM().
receivedASL
int veins::ASLAppRSU::receivedASL =0 protected
Referenced by handleLowerMsg().
receivedASLBSM
int veins::ASLAppRSU::receivedASLBSM =0 protected
Referenced by handleLowerMsg().
serviceRate
double veins::ASLAppRSU::serviceRate = 1800/3600 protected
Referenced by onASLBSM().
speedLimit
double veins::ASLAppRSU::speedLimit = 15 protected
Referenced by onASLBSM().
tlsInterface
TraCITrafficLightInterface* veins::ASLAppRSU::tlsInterface protected
Referenced by initialize(), and onASLBSM().
tlsTraci
TraCICommandInterface::Trafficlight* veins::ASLAppRSU::tlsTraci protected
Referenced by initialize().
traci
TraCICommandInterface* veins::ASLAppRSU::traci protected
Referenced by initialize().
vehiclesInFront
int veins::ASLAppRSU::vehiclesInFront = 0 protected
Referenced by onASLBSM().
The documentation for this class was generated from the following files:
ASLAppRSU.h
ASLAppRSU.cc